### ISSUE TITLE
Please drop this repo

### ISSUE THREAD

**Issue by bgermann** [Lesik/unrar-free#2]
The project was revived at https://gitlab.com/bgermann/unrar-free which holds the Gna! repo's history.
Please remove this repo in favour of that one.

**Comment by Lesik** [comment]
Hi @bgermann, great to hear that development on unrar-free has resumed! As your name (Bastian Germann) was not mentioned in the [AUTHORS file](https://github.com/Lesik/unrar-free/blob/5c811812a20e4097f90e32e11ce8446a1ceeabae/AUTHORS) at the time Gna! shut down, I assume that you were not part of the original development team. I was wondering if the original team has officially transferred the project over to you, or is it more like a fork?

**Comment by bgermann** [comment]
It is a fork that has replaced unrar-free in most places (e.g., Linux distributions) where the Gna! version was around.

**Comment by Lesik** [comment]
That's true [(at least for Debian)](https://tracker.debian.org/news/1265765/accepted-unrar-free-1002-01-source-into-unstable/). I will archive this repository.
